application: pongography
version: 1
runtime: python27
api_version: 1

threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
<<<<<<< HEAD
  script: pong.application
=======
  script: pongography.application
>>>>>>> 172333e0bf521436d8aea119f089a4f8f950fd2a


libraries:
- name: webapp2
  version: latest
